


CREATE TABLE aggiudicatari_validati("Codice Univoco Submisura" VARCHAR, "Descrizione Submisura" VARCHAR, "CUP" VARCHAR, "Codice Locale Progetto" VARCHAR, "CIG" VARCHAR, "Modalità di realizzazione" VARCHAR, "Codice interno PDA" VARCHAR, "Oggetto principale del contratto" VARCHAR, "Oggetto Gara" VARCHAR, "Data pubblicazione del CIG" DATE, "Codice motivo assenza CIG" VARCHAR, "Descrizione motivo assenza CIG" VARCHAR, "Descrizione procedura di aggiudicazione" VARCHAR, "Importo complessivo gara" FLOAT, "Importo aggiudicazione" FLOAT, "Data aggiudicazione definitiva" DATE, "Codice Fiscale - P IVA Aggiudicatario" VARCHAR, "Denominazione Aggiudicatario" VARCHAR, "Forma giuridica Aggiudicatario" VARCHAR, "Descrizione forma giuridica Aggiudicatario" VARCHAR, "Codice ATECO Aggiudicatario" VARCHAR, "Data di aggiornamento" DATE);
CREATE TABLE progetti_universo("Programma" VARCHAR, "Missione" VARCHAR, "Descrizione Missione" VARCHAR, "Componente" VARCHAR, "Descrizione Componente" VARCHAR, "ID Misura" VARCHAR, "Codice Univoco Misura" VARCHAR, "Descrizione Misura" VARCHAR, "ID Submisura" VARCHAR, "Codice CID" VARCHAR, "Codice Univoco Submisura" VARCHAR, "Descrizione Submisura" VARCHAR, "Amministrazione Titolare" VARCHAR, "Codice identificativo Procedura di Attivazione" VARCHAR, "Titolo procedura" VARCHAR, "Tipologia procedura di attivazione" VARCHAR, "CUP" VARCHAR, "Codice Locale Progetto" VARCHAR, "Stato CUP" VARCHAR, "CUP Codice Natura" VARCHAR, "CUP Descrizione Natura" VARCHAR, "CUP Codice Tipologia" VARCHAR, "CUP Descrizione Tipologia" VARCHAR, "CUP Codice Settore" VARCHAR, "CUP Descrizione Settore" VARCHAR, "CUP Codice Sottosettore" VARCHAR, "CUP Descrizione Sottosettore" VARCHAR, "CUP Codice Categoria" VARCHAR, "CUP Descrizione Categoria" VARCHAR, "Titolo progetto" VARCHAR, "Sintesi progetto" VARCHAR, "Descrizione Tipo Aiuto" VARCHAR, "Finanziamento - Stato" FLOAT, "Finanziamento UE (diverso da PNRR)" FLOAT, "Finanziamento Regione" FLOAT, "Finanziamento Provincia" FLOAT, "Finanziamento Comune" FLOAT, "Finanziamento Altro Pubblico" FLOAT, "Finanziamento Privato" FLOAT, "Finanziamento Da Reperire" FLOAT, "Finanziamento PNRR" FLOAT, "Finanziamento PNC" FLOAT, "Altri fondi" FLOAT, "Finanziamento Totale" FLOAT, "Finanziamento Totale Pubblico" FLOAT, "Finanziamento Totale Pubblico Netto" FLOAT, "Soggetto attuatore" VARCHAR, "Codice fiscale soggetto attuatore" VARCHAR, "Flag progetti in essere" VARCHAR, "Data di Estrazione" DATE);
CREATE TABLE progetti_validati("Programma" VARCHAR, "Missione" VARCHAR, "Descrizione Missione" VARCHAR, "Componente" VARCHAR, "Descrizione Componente" VARCHAR, "ID Misura" VARCHAR, "Codice Univoco Misura" VARCHAR, "Descrizione Misura" VARCHAR, "ID Submisura" VARCHAR, "Codice CID" VARCHAR, "Codice Univoco Submisura" VARCHAR, "Descrizione Submisura" VARCHAR, "Amministrazione Titolare" VARCHAR, "Codice identificativo Procedura di Attivazione" VARCHAR, "Titolo procedura" VARCHAR, "Tipologia procedura di attivazione" VARCHAR, "CUP" VARCHAR, "Codice Locale Progetto" VARCHAR, "Stato CUP" VARCHAR, "CUP Codice Natura" VARCHAR, "CUP Descrizione Natura" VARCHAR, "CUP Codice Tipologia" VARCHAR, "CUP Descrizione Tipologia" VARCHAR, "CUP Codice Settore" VARCHAR, "CUP Descrizione Settore" VARCHAR, "CUP Codice Sottosettore" VARCHAR, "CUP Descrizione Sottosettore" VARCHAR, "CUP Codice Categoria" VARCHAR, "CUP Descrizione Categoria" VARCHAR, "Titolo progetto" VARCHAR, "Sintesi progetto" VARCHAR, "Descrizione Tipo Aiuto" VARCHAR, "Finanziamento - Stato" FLOAT, "Finanziamento UE (diverso da PNRR)" FLOAT, "Finanziamento Regione" FLOAT, "Finanziamento Provincia" FLOAT, "Finanziamento Comune" FLOAT, "Finanziamento Altro Pubblico" FLOAT, "Finanziamento Privato" FLOAT, "Finanziamento Da Reperire" FLOAT, "Finanziamento PNRR" FLOAT, "Finanziamento PNC" FLOAT, "Altri fondi" FLOAT, "Finanziamento Totale" FLOAT, "Finanziamento Totale Pubblico" FLOAT, "Finanziamento Totale Pubblico Netto" FLOAT, "Soggetto attuatore" VARCHAR, "Codice fiscale soggetto attuatore" VARCHAR, "Flag progetti in essere" VARCHAR, "Data aggiornamento" DATE);
CREATE TABLE aggiudicatari_universo("Codice Univoco Submisura" VARCHAR, "Descrizione Submisura" VARCHAR, "CUP" VARCHAR, "Codice Locale Progetto" VARCHAR, "CIG" VARCHAR, "Modalità di realizzazione" VARCHAR, "Codice interno PDA" VARCHAR, "Oggetto principale del contratto" VARCHAR, "Oggetto Gara" VARCHAR, "Data pubblicazione del CIG" DATE, "Codice motivo assenza CIG" VARCHAR, "Descrizione motivo assenza CIG" VARCHAR, "Descrizione procedura di aggiudicazione" VARCHAR, "Importo complessivo gara" FLOAT, "Importo aggiudicazione" FLOAT, "Data aggiudicazione definitiva" DATE, "Codice Fiscale - P IVA Aggiudicatario" VARCHAR, "Denominazione Aggiudicatario" VARCHAR, "Forma giuridica Aggiudicatario" VARCHAR, "Descrizione forma giuridica Aggiudicatario" VARCHAR, "Codice ATECO Aggiudicatario" VARCHAR, "Data di Estrazione" DATE);
CREATE TABLE localizzazioni_validate("Codice Univoco Submisura" VARCHAR, "Descrizione Submisura" VARCHAR, "CUP" VARCHAR, "Codice Locale Progetto" VARCHAR, "Codice Regione" BIGINT, "Descrizione Regione" VARCHAR, "Codice Provincia" BIGINT, "Descrizione Provincia" VARCHAR, "Codice Comune" BIGINT, "Descrizione Comune" VARCHAR, "Indirizzo" VARCHAR, "Cap" BIGINT, "Data di aggiornamento" DATE, "COD_ISTAT_COMUNE" VARCHAR);
CREATE TABLE soggetti_validati("Descrizione Submisura" VARCHAR, "CUP" VARCHAR, "Codice Locale Progetto" VARCHAR, "Ruolo soggetto" VARCHAR, "Descrizione del ruolo del soggetto" VARCHAR, "Codice fiscale soggetto" VARCHAR, "Denominazione" VARCHAR, "Forma giuridica" VARCHAR, "Descrizione forma giuridica" VARCHAR, "Codice ATECO" VARCHAR, "Data di aggiornamento" DATE);
CREATE TABLE localizzazioni_universo("Codice Univoco submisura" VARCHAR, "Descrizione Submisura" VARCHAR, "CUP" VARCHAR, "Codice Locale Progetto" VARCHAR, "Regione" BIGINT, "Descrizione Regione" VARCHAR, "Provincia" BIGINT, "Descrizione Provincia" VARCHAR, "Comune" BIGINT, "Descrizione Comune" VARCHAR, "Indirizzo" VARCHAR, "CAP" BIGINT, "Data di Estrazione" DATE, "COD_ISTAT_COMUNE" VARCHAR);




